In [7]:
import skimage.io
import matplotlib.pyplot as plt
import numpy as np
import cv2

im2=skimage.io.imread('godong.jfif')
np.set_printoptions(threshold=np.inf)    
print(im2)

[[[158 216 236]
  [157 215 235]
  [157 215 235]
  [157 215 235]
  [159 217 237]
  [160 218 238]
  [159 217 237]
  [158 216 236]
  [160 218 238]
  [148 206 226]
  [151 209 229]
  [170 228 248]
  [174 232 252]
  [158 216 236]
  [149 207 227]
  [154 212 232]
  [174 231 251]
  [168 225 245]
  [162 219 239]
  [161 218 238]
  [163 220 240]
  [165 222 242]
  [164 221 241]
  [162 219 239]
  [158 215 235]
  [174 231 251]
  [158 215 235]
  [167 224 244]
  [156 213 233]
  [167 224 244]
  [168 225 245]
  [160 217 237]
  [166 221 241]
  [166 221 241]
  [166 221 241]
  [166 221 241]
  [166 221 241]
  [166 221 241]
  [166 221 241]
  [166 221 241]
  [168 223 243]
  [164 219 239]
  [171 226 246]
  [162 217 237]
  [172 227 247]
  [162 217 237]
  [170 225 245]
  [166 221 241]
  [164 219 239]
  [162 217 237]
  [188 243 255]
  [170 225 245]
  [168 223 243]
  [167 222 242]
  [168 223 243]
  [184 239 255]
  [167 222 242]
  [167 222 242]
  [167 222 242]
  [168 223 243]
  [168 223 243]
  [169 224 244]
  [169 2

In [9]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('godong.jfif')
img_resize = cv2.resize(img, (208, 278))

edged = cv2.Canny(img_resize, 150, 260) 

cv2.imshow("Original Image",img_resize)
cv2.imshow("Edged Image", edged)

cv2.waitKey(0)
cv2.destroyAllWindows()
